### ISSUE TITLE
The POC Student should not see the Discussion tab 

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#25]
Discussions in POCs raise a number of issues that we can't resolve right now. Easier to remove the tab.

**Comment by pwilkins** [comment]
Removing the Discussion tab still allows Discussion components that exist in the courseware to create Posts and Questions, although without the Discussion tab, students are unable to view them.  **Decision:** It is the responsibility of the POC course team to communicate this problem to their students, or, remove those discussion items from the courseware.

**Comment by cewing** [comment]
As it turns out, the display of the "discussion" tab is controlled by the same code that is at issue in #18.  I believe, therefore, that we cannot resolve this issue without the same solution that is being pursued for that issue.  

We just need to be able to interrogate the user in the context of the logic that chooses to display tabs.

**Comment by cewing** [comment]
As @chrisrossi pointed out, the call signature for the `get_current_poc` method was misleading.  The active user is no longer required in order to get the current POC and so I have been able to fix this without the work needed for fixing #18.

This is now ready for testing.

**Comment by pdpinch** [comment]
Awesome! Thank you @cewing 

Sorry for taking so long to close this.
