### ISSUE TITLE
Move CCX-related field overrides to happen at the modulestore layer... 

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/edx-platform#79]
...  so that content-related services like search and course structures can query with the new CCX course keys.

Depends on #43

**Comment by pdpinch** [comment]
@bdero this was a request from Dave Ormsbee. Do you think this would have any affect on 

a) our memory issues
b) where we might control overrides at a per-course level?

**Comment by bdero** [comment]
I'm actually not too sure what this means. Is this CCX-specific, or is this a proposal for reimplementing field overrides to not be a field data wrapper? What does it mean for e.g. the content search feature to "query with the new CCX course keys"? Is this because the field data will only be filtered while rendering, but features like the search service query the course tree in a more direct way?

**Comment by bdero** [comment]
If I'm guessing right, the intention is to make field override providers work when trying to read field data - in which case I don't think it will have an effect on the performance/memory problem.

**Comment by pdpinch** [comment]
I think you're right @bdero. In fact, this might expand the set of cases where we run into memory issues, depending on how these other services walk the course tree.

**Comment by pdpinch** [comment]
According to Dave Ormsbee at edX, this was already addressed in https://github.com/edx/edx-platform/pull/8519
